- name: Check and configure Keepalived
  hosts: controller
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  tasks:
    - name: Install Keepalived package
      yum:
        name: keepalived
        state: present

    - name: Ensure directory exists for keepalived.conf
      file:
        path: /etc/keepalived
        state: directory

    - name: Check if keepalived.conf exists
      stat:
        path: /etc/keepalived/keepalived.conf
      register: keepalived_conf

    - name: Backup existing keepalived.conf if it exists
      when: keepalived_conf.stat.exists
      command: mv -v /etc/keepalived/keepalived.conf /etc/keepalived/keepalived.conf.bak

    - name: Ensure keepalived.conf file exists
      file:
        path: /etc/keepalived/keepalived.conf
        state: touch

    - name: Generate new keepalived.conf
      blockinfile:
        path: /etc/keepalived/keepalived.conf
        block: |
          global_defs {
            router_id {{ ansible_hostname}}
            vrrp_skip_check_adv_addr
          }

          vrrp_instance openstack-internal-vip-ip {
          {% if ansible_hostname == 'controller-1' %}
            state MASTER
            priority 100
          {% else %}
            state BACKUP
            priority 90
          {% endif %}
            interface eth0
            virtual_router_id 3
            advert_int 1
            authentication {
                auth_type NONE # No authentication
            }
            virtual_ipaddress {
                10.66.66.3
            }
          }

          vrrp_instance openstack-external-vip-ip {
          {% if ansible_hostname == 'controller-1' %}
            state MASTER
            priority 100
          {% else %}
            state BACKUP
            priority 90
          {% endif %}
            interface eth1
            virtual_router_id 3
            advert_int 1
            authentication {
                auth_type NONE # No authentication
            }
            virtual_ipaddress {
                10.166.166.3
            }
          }
      notify: Restart Keepalived service

  handlers:
    - name: Restart Keepalived service
      service:
        name: keepalived
        state: restarted
        enabled: yes
