- name: Memcache setup
  hosts: controller
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  tasks:
    - name: Install memcached and python3-memcached
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - memcached
        - python3-memcached

    - name: Get eth0 IP address
      shell: ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'|head -n1
      register: eth0_ip

    - name: Alter memcached configuration file
      replace:
        path: /etc/sysconfig/memcached
        regexp: '^OPTIONS="(.*)"'
        replace: 'OPTIONS="-l {{ eth0_ip.stdout }}"'
      notify: Restart memcached

    - name: Ensure memcached service is enabled and restarted
      ansible.builtin.service:
        name: memcached
        state: started
        enabled: yes

  handlers:
    - name: Restart memcached
      ansible.builtin.service:
        name: memcached
        state: restarted
        enabled: yes
