- name: Install and configure MariaDB
  hosts: controller
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  tasks:
    - name: Check if MySQL is installed
      stat:
        path: /usr/bin/mysql
      register: mysql_installed

    - name: Ensure required packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - mariadb
        - mariadb-server
        - python3-PyMySQL
        - galera
        - expect
      when: not mysql_installed.stat.exists

    - name: Ensure mariadb service is started and enabled
      when: not mysql_installed.stat.exists
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Get eth0 IP address
      shell: ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n1
      register: eth0_ip

    - name: Create or overwrite my.cnf configuration file
      copy:
        dest: /etc/my.cnf.d/openstack.cnf
        content: |
          [mysqld]
          bind-address = {{ eth0_ip.stdout }}
          default-storage-engine = innodb
          innodb_file_per_table = on
          max_connections = 4096
          collation-server = utf8_general_ci
          character-set-server = utf8
      notify: Restart MariaDB

    - name: Run mysql_secure_installation
      expect:
        command: mysql_secure_installation
        responses:
          "Enter current password for root": ""
          "Set root password": "n"
          "Remove anonymous users": "y"
          "Disallow root login remotely": "y"
          "Remove test database": "y"
          "Reload privilege tables now": "y"
        timeout: 1
      register: secure_mariadb
      failed_when: "'... Failed!' in secure_mariadb.stdout_lines"

  handlers:
    - name: Restart MariaDB
      systemd:
        name: mariadb
        state: restarted
        enabled: yes