- name: Get interface connections, change names, and disable IPv6 using nmcli and Ansible
  hosts: rocky_linux
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  gather_facts: yes
  tasks:
    - name: Comment out line in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^::1\s+localhost\s+localhost.localdomain\s+localhost6\s+localhost6.localdomain6$'
        line: "# ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6"
        backup: no

    - name: Get current network connections
      shell: nmcli -t -f NAME,DEVICE con show | cut -d":" -f1,2 | grep -i eth
      register: current_connections
      changed_when: false

    - name: Modify connection names
      shell: nmcli con mod "{{ item.split(':')[0] }}" connection.id "{{ item.split(':')[1] }}"
      loop: "{{ current_connections.stdout_lines }}"
      when: current_connections.stdout_lines | length > 0
      ignore_errors: yes # Ignore errors if the connection name is already changed

    - name: Disable IPv6 on interface connections
      shell: nmcli con mod "{{ item.split(':')[1] }}" ipv6.method "disabled"
      loop: "{{ current_connections.stdout_lines }}"
      when: current_connections.stdout_lines | length > 0
      ignore_errors: yes # Ignore errors if IPv6 is already disabled

    - name: Refresh interface connections
      ansible.builtin.shell: nmcli con up "{{ item.split(':')[1] }}"
      loop: "{{ current_connections.stdout_lines }}"
      when: current_connections.stdout_lines | length > 0
