- name: Configuring Object Storage mountpoint
  hosts: rocky_linux
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Install s3fs-fuse package
      yum:
        name: s3fs-fuse
        state: present
        update_cache: yes

    - name: Create directory /object-storage
      file:
        path: /object-storage
        state: directory
        mode: "0755"

    - name: Populate /etc/passwd-s3fs with credentials from template
      template:
        src: passwd-s3fs.j2
        dest: /etc/passwd-s3fs
        mode: "0400"

    - name: Check if /etc/fstab entry already exists
      shell: grep -q 'openstack-object-storage /object-storage fuse.s3fs' /etc/fstab
      register: fstab_check
      ignore_errors: true
      failed_when: false

    - name: Add mount entry to /etc/fstab if not already present
      lineinfile:
        path: /etc/fstab
        line: "openstack-object-storage /object-storage fuse.s3fs  nonempty,passwd_file=/etc/passwd-s3fs,allow_other,url=https://object.wse.zone,use_path_request_style 0 0"
        create: yes
      when: fstab_check.rc != 0 # Only add if the entry doesn't exist

    - name: Mount the object storage if not already mounted
      mount:
        src: openstack-object-storage
        path: /object-storage
        fstype: fuse.s3fs
        opts: "nonempty,passwd_file=/etc/passwd-s3fs,allow_other,url=https://object.wse.zone,use_path_request_style"
        state: mounted
        passno: 0
        dump: 0
      when: fstab_check.rc != 0 # Only mount if the entry doesn't exist in fstab
