- name: Configure system parameters
  hosts: rocky_linux
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  tasks:
    - name: Set vm.swappiness using sysctl
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
      register: swappiness_result
      changed_when: swappiness_result.changed

    - name: Configure net.ipv6.conf.all.disable_ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present
      register: ipv6_result
      changed_when: ipv6_result.changed

    - name: Reload sysctl if any configuration changed
      command: sysctl -p
      when: swappiness_result.changed or ipv6_result.changed
    - name: Disable SELinux temporarily
      selinux:
        policy: targeted # Specify the SELinux policy (e.g., targeted, strict, mls)
        state: permissive

    - name: Update SELinux configuration
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=permissive"

- name: Configure net.ipv4.ip_forward only on "vpn" hosts
  hosts: vpn
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Additional SSH options
  become: yes
  tasks:
    - name: Configure net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
      register: ipv4_result
      changed_when: ipv4_result.changed

    - name: Reload sysctl if any configuration changed
      command: sysctl -p
      when: ipv4_result.changed
